### ISSUE TITLE
Create simlink to latest log

### ISSUE THREAD

**Issue by J0las** [THI-Drone/deployment#1]
https://github.com/THI-Drone/deployment/blob/d96b5bc8812bee00634af02c11979e98ff7b71be/docker_run.sh#L2

**Comment by J0las** [comment]
Maybe a better place to create that symlink would be inside the ros launch file

**Comment by Philipp66904** [comment]
Implemented in launch file

**Comment by Philipp66904** [comment]
See: https://github.com/THI-Drone/mission_software_launch/pull/12
